### ISSUE TITLE
git-sync doesn't work when server is stopped

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/data100-19s#34]
@papajohn emailed:
> I tried to load Data 100 hw 1 using this link and received the error "service unavailable"
> 
> https://data100.datahub.berkeley.edu/hub/user-redirect/git-sync?repo=https://github.com/DS-100/sp19&subPath=hw/hw1/hw1.ipynb
> 
> After I explicitly first went to data100.datahub.berkeley.edu and waited for my server to start, the git-sync link worked fine.
> 
> Another student said that they experienced the same problem, and the same fix worked for them.
> 
> Any hope of getting git-sync to work even when someone's server is off?

**Comment by ryanlovett** [comment]
@papajohn @simon-mo git-sync should start user servers if they are not already running. I do recall however that if the user doesn't exist yet on the hub then they might run into this. I'll need to double-check. In the interim I'm going to manually create the users based on the SIS roster.

**Comment by papajohn** [comment]
My user definitely existed already when I had this problem.

**Comment by ryanlovett** [comment]
Adding a data point, when I visit

https://data100.datahub.berkeley.edu/user/denero/git-sync?repo=https://github.com/DS-100/sp19&subPath=hw/hw1/hw1.ipynb

as a hub admin, the user server starts and git-sync operates normally.

I'm going to try user-redirect/git-sync as a user who has never logged in.

**Comment by ryanlovett** [comment]
I was unable to reproduce as the new user "courses-stat". I'm thinking that this isn't a git-sync issue.

Can you please slack me the name of users with "service unavailable" ?

Edit: I'm checking the users in the piazza post.

**Comment by ryanlovett** [comment]
I believe the cause of this is fixed by #35.

We upscaled the cluster on Monday, but the singleuser environment wasn't automatically pulled onto the node. When user servers were started on these new nodes, dockerd had to fetch the image from docker hub and some users timed out while the transfer was underway.
