### ISSUE TITLE
Bump Memory for Instructor SPA Account

### ISSUE THREAD

**Issue by simon-mo** [berkeley-dsep-infra/data100-19s#85]
Hi @ryanlovett 

Any chance we can bump the memory for the instructor spa account to 5G?

I forgot how to do it and do it correctly.

Ideally we want for the instructor account:
```
data100.instructors
guarantee: 4G
no limit
```
Thanks

**Comment by ryanlovett** [comment]
#86 raises it from 4G to 5G.

You may recall that you use the git-crypt key to unlock the secrets.
